version: "3"

services:

    mongo:
        container_name: 'mongo'
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
        command: '--smallfiles --bind_ip mongo'

    server:
        container_name: 'server'
        build: ./server
        ports:
            - 3001:3001
        volumes:
            - ./server:/data
        depends_on:
            - mongo
        environment:
            - DATABASE_URL=mongo:27017

    client:
        container_name: 'client'
        build: ./client
        ports:
            - 3002:3002
        volumes:
            - ./client:/data
        environment:
            - API_URL=http://localhost:3002/
            - PORT=3002